### ISSUE TITLE
IRC connection failing

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#17]
```
[09:49:53 WARN]: java.net.SocketException: Connection reset
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[09:49:53 WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[09:49:53 WARN]: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[09:49:53 WARN]: 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
[09:49:53 WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[09:49:53 WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//dev.polarian.ircj.IrcClient.connect(IrcClient.java:315)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//xyz.crafttogether.chatbridge.irc.IrcConnection.run(IrcConnection.java:48)
[09:49:53 WARN]: java.net.SocketException: Broken pipe
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[09:49:53 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[09:49:53 WARN]: 	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
[09:49:53 WARN]: 	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
[09:49:53 WARN]: 	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
[09:49:53 WARN]: 	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//dev.polarian.ircj.IrcClient.sendCommand(IrcClient.java:276)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//dev.polarian.ircj.Commands.disconnect(Commands.java:112)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//dev.polarian.ircj.IrcClient.connect(IrcClient.java:339)
[09:49:53 WARN]: 	at chat-bridge-1.3-SNAPSHOT-2.jar//xyz.crafttogether.chatbridge.irc.IrcConnection.run(IrcConnection.java:48)
```

**Comment by ghost** [comment]
fixed in commit d2affd6e18599debf4e411ba9cf3215654acc10d
