### ISSUE TITLE
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#19]
```
[13:06:33 ERROR]: Error occurred while enabling ChatBridge v1.3-SNAPSHOT-3 (Is it up to date?)
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at okhttp3.HttpUrl.get(HttpUrl.java:917) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at okhttp3.Request$Builder.url(Request.java:165) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at xyz.crafttogether.chatbridge.utilities.Webhook.send(Webhook.java:74) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at xyz.crafttogether.chatbridge.discord.DiscordMessageSender.send(DiscordMessageSender.java:44) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at xyz.crafttogether.chatbridge.ChatBridge.onEnable(ChatBridge.java:171) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.18.1.jar:git-Paper-197]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:06:33 INFO]: [ChatBridge] Disabling ChatBridge v1.3-SNAPSHOT-3
[13:06:33 ERROR]: Error occurred while disabling ChatBridge v1.3-SNAPSHOT-3 (Is it up to date?)
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at okhttp3.HttpUrl.get(HttpUrl.java:917) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at okhttp3.Request$Builder.url(Request.java:165) ~[craftcore-1.0-SNAPSHOT-6.jar:?]
	at xyz.crafttogether.chatbridge.utilities.Webhook.send(Webhook.java:74) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at xyz.crafttogether.chatbridge.discord.DiscordMessageSender.send(DiscordMessageSender.java:44) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at xyz.crafttogether.chatbridge.ChatBridge.onDisable(ChatBridge.java:197) ~[chat-bridge-1.3-SNAPSHOT-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.18.1.jar:git-Paper-197]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-197]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ghost** [comment]
@M5rian deal with this please, thanks

**Comment by ghost** [comment]
nevermind, due to invalid configuration
