### ISSUE TITLE
Zip file closed

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#25]
```
[12:33:18] [IRC-Thread/DEBUG]: [dev.polarian.ircj.IrcThread] :Polaris.Irc NOTICE Notch :Connection statistics: client 1.8 kb, server 3.4 kb.
[12:33:18] [IRC-Thread/DEBUG]: [dev.polarian.ircj.IrcThread] ERROR :"Chat bridge has been disabled"
[12:33:18] [IRC-Thread/WARN]: [dev.polarian.ircj.IrcThread] Disconnected from IRC server
[12:33:18] [IRC-Thread/WARN]: java.lang.IllegalStateException: zip file closed
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[12:33:18] [IRC-Thread/WARN]:   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[12:33:18] [IRC-Thread/WARN]:   at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[12:33:18] [IRC-Thread/WARN]:   at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:33:18] [IRC-Thread/WARN]:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:33:18] [IRC-Thread/WARN]:   at chat-bridge-1.3-SNAPSHOT-11.jar//dev.polarian.ircj.IrcThread.run(IrcThread.java:69)
```

**Comment by ghost** [comment]
Seems to be fixed in commit 0354b5043ae2cbfe0a676762b43d57340222c3a9
